language: python # Set the build language to Python

python: 3.8 # Set the version of Python to use

install:
    - pip install pipenv # Install the required dependencies
    - pipenv install

script:
    - pipenv run build # Build a local version of the docs

deploy: # Deploy documentation to Github in the gh_pages branch
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
        branch: dev
    target-branch: master
    keep-history: true
